export const FETCH_STUDENTS_DETAILS = 'FETCH_STUDENTS_DETAILS';
export const SORT_BY_APLHABETICAL = 'SORT_BY_APLHABETICAL';
export const SORT_BY_MARKS = 'SORT_BY_MARKS';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const AUTHENTICATION='AUTHENTICATION';